apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd-upgrade
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd-upgrade
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
  namespace: argocd-upgrade
spec:
  replicas: 2

